-- Inserting into CATEGORY TABLE

INSERT INTO category (CAT_NAME) VALUES ('BOOKS');
INSERT INTO category (CAT_NAME) VALUES ('GAMES');
INSERT INTO category (CAT_NAME) VALUES ('GROCERIES');
INSERT INTO category (CAT_NAME) VALUES ('ELECTRONICS');
INSERT INTO category (CAT_NAME) VALUES ('CLOTHES');