-- Inserting into CUSTOMER TABLE

INSERT INTO customer (CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER) VALUES ('AAKASH',9999999999,'DELHI','M');
INSERT INTO customer (CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER) VALUES ('AMAN',9785463215,'NOIDA','M');
INSERT INTO customer (CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER) VALUES ('NEHA',9999999999,'MUMBAI','F');
INSERT INTO customer (CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER) VALUES ('MEGHA',9994562399,'KOLKATA','F');
INSERT INTO customer (CUS_NAME,CUS_PHONE,CUS_CITY,CUS_GENDER) VALUES ('PULKIT',7895999999,'LUCKNOW','M');