-- Inserting into RATING TABLE

INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (101,4);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (102,3);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (103,1);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (104,2);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (105,4);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (106,3);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (107,4);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (109,3);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (110,5);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (111,3);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (112,4);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (113,2);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (114,1);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (115,1);
INSERT INTO rating (ORD_ID,RAT_RATSTARS) VALUES (116,0);