-- Inserting into SUPPLIER TABLE

INSERT INTO supplier (SUPP_NAME,SUPP_CITY,SUPP_PHONE) VALUES ('Rajesh Retails','Delhi',1234567890);
INSERT INTO supplier (SUPP_NAME,SUPP_CITY,SUPP_PHONE) VALUES ('Appario Ltd.','Mumbai',2589631470);
INSERT INTO supplier (SUPP_NAME,SUPP_CITY,SUPP_PHONE) VALUES ('Knome products','Banglore',9785462315);
INSERT INTO supplier (SUPP_NAME,SUPP_CITY,SUPP_PHONE) VALUES ('Bansal Retails','Kochi',8975463285);
INSERT INTO supplier (SUPP_NAME,SUPP_CITY,SUPP_PHONE) VALUES ('Mittal Ltd.','Lucknow',7898456532);